{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 7.671523788740413, 'rmse': 2.7697515752753734, 'mape': 0.061603894975932834, 'mae': 2.1, 'smape': 6.11, 'r2': 0.0017598912391660892, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 463.1897615131579, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 0.8890586037517384, 'rmse': 0.942899042184124, 'mape': 0.009088064667006719, 'mae': 0.8, 'smape': 0.91, 'r2': -0.8371495481823006, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 463.1897615131579, 'metric': 'mem'}\n",
      "[Server] training_time: 3.498711585998535 s\n",
      "[Server] eval_time: 0.5808563232421875 s\n",
      "[Local] Memory usage: 304.65625 MB\n",
      "[Local] Total processing time: 11.2026 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n"
     ]
    }
   ],
   "source": [
    "!python train_dataclay.py --name_experiment \"Ryzen-Mac_server\" --client_experiment \"./Ryzen-Mac_client\" --server_ip \"ceadaridg6.ucd.ie\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Password:\n",
      "sudo: a password is required\n"
     ]
    }
   ],
   "source": [
    "# !sudo chmod +x train_dataclay.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 7.60471057377511, 'rmse': 2.7576639704240815, 'mape': 0.061740184493744604, 'mae': 2.14, 'smape': 6.25, 'r2': 0.0104538134390183, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 462.70162259615387, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 0.6646328487158168, 'rmse': 0.8152501755386605, 'mape': 0.006574092412082041, 'mae': 0.58, 'smape': 0.66, 'r2': -0.3733964584255234, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 462.70162259615387, 'metric': 'mem'}\n",
      "[Server] training_time: 3.560082197189331 s\n",
      "[Server] eval_time: 0.36505579948425293 s\n",
      "[Local] Memory usage: 305.875 MB\n",
      "[Local] Total processing time: 11.3061 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 8.060487183689556, 'rmse': 2.83909971358696, 'mape': 0.06288444209836783, 'mae': 2.17, 'smape': 6.33, 'r2': -0.04885311243135604, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 465.7974028716216, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 1.0984124604774388, 'rmse': 1.0480517451335305, 'mape': 0.010009022080688428, 'mae': 0.88, 'smape': 1.01, 'r2': -1.2697580867767289, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 465.7974028716216, 'metric': 'mem'}\n",
      "[Server] training_time: 3.3125927448272705 s\n",
      "[Server] eval_time: 0.34649229049682617 s\n",
      "[Local] Memory usage: 304.390625 MB\n",
      "[Local] Total processing time: 10.5734 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 7.214426157881399, 'rmse': 2.685968383633992, 'mape': 0.06002992552669379, 'mae': 2.07, 'smape': 6.04, 'r2': 0.06123871204563058, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 467.1892947635135, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 0.5379712974520147, 'rmse': 0.7334652666977589, 'mape': 0.006302534235246396, 'mae': 0.56, 'smape': 0.63, 'r2': -0.1116631928180496, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 467.1892947635135, 'metric': 'mem'}\n",
      "[Server] training_time: 3.291232109069824 s\n",
      "[Server] eval_time: 0.33991003036499023 s\n",
      "[Local] Memory usage: 304.546875 MB\n",
      "[Local] Total processing time: 7.4946 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 7.910654142946797, 'rmse': 2.8125885129088464, 'mape': 0.06332447238364818, 'mae': 2.18, 'smape': 6.37, 'r2': -0.02935641855333615, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 468.17578125, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 0.9939227821738448, 'rmse': 0.9969567604333925, 'mape': 0.009805476068428215, 'mae': 0.87, 'smape': 0.99, 'r2': -1.0538407507596248, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 468.17578125, 'metric': 'mem'}\n",
      "[Server] training_time: 3.381169557571411 s\n",
      "[Server] eval_time: 0.35039758682250977 s\n",
      "[Local] Memory usage: 304.71875 MB\n",
      "[Local] Total processing time: 7.6300 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 7.946537805792169, 'rmse': 2.818960412242813, 'mape': 0.06285483196810561, 'mae': 2.17, 'smape': 6.3, 'r2': -0.034025701017672105, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 468.67578125, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 1.263202863652193, 'rmse': 1.1239229794128212, 'mape': 0.011259515029249854, 'mae': 0.99, 'smape': 1.13, 'r2': -1.6102807626270352, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 468.67578125, 'metric': 'mem'}\n",
      "[Server] training_time: 3.352304458618164 s\n",
      "[Server] eval_time: 0.34869885444641113 s\n",
      "[Local] Memory usage: 303.828125 MB\n",
      "[Local] Total processing time: 7.5783 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 7.270655369752019, 'rmse': 2.6964152813971403, 'mape': 0.06011497676910868, 'mae': 2.07, 'smape': 6.02, 'r2': 0.05392200989896634, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 469.1892947635135, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 0.46908478414237353, 'rmse': 0.6848976450115547, 'mape': 0.005981711033019283, 'mae': 0.53, 'smape': 0.6, 'r2': 0.030683809132791895, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 469.1892947635135, 'metric': 'mem'}\n",
      "[Server] training_time: 3.2860381603240967 s\n",
      "[Server] eval_time: 0.3395090103149414 s\n",
      "[Local] Memory usage: 302.0625 MB\n",
      "[Local] Total processing time: 7.5851 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 7.831778197634899, 'rmse': 2.798531435884703, 'mape': 0.06312914523302607, 'mae': 2.19, 'smape': 6.41, 'r2': -0.019092860178880455, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 469.6896701388889, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 1.3377554706997965, 'rmse': 1.1566137949634685, 'mape': 0.011556062161358393, 'mae': 1.02, 'smape': 1.16, 'r2': -1.7643361733450034, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 469.6896701388889, 'metric': 'mem'}\n",
      "[Server] training_time: 3.3638863563537598 s\n",
      "[Server] eval_time: 0.35152363777160645 s\n",
      "[Local] Memory usage: 304.875 MB\n",
      "[Local] Total processing time: 10.5302 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 8.673872686988163, 'rmse': 2.945143916175942, 'mape': 0.06684334659800488, 'mae': 2.33, 'smape': 6.85, 'r2': -0.12866854785030224, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 469.70280827702703, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 1.7614585153817943, 'rmse': 1.3271995009725532, 'mape': 0.011142862880916673, 'mae': 0.98, 'smape': 1.13, 'r2': -2.6398755965238605, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 469.70280827702703, 'metric': 'mem'}\n",
      "[Server] training_time: 3.3133304119110107 s\n",
      "[Server] eval_time: 0.34853410720825195 s\n",
      "[Local] Memory usage: 303.703125 MB\n",
      "[Local] Total processing time: 10.6118 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 7.801894142835875, 'rmse': 2.7931870941338452, 'mape': 0.06012959434231749, 'mae': 2.05, 'smape': 5.95, 'r2': -0.01520426347576187, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 470.1896701388889, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 0.4508260884970267, 'rmse': 0.6714358409386758, 'mape': 0.00590044707716552, 'mae': 0.52, 'smape': 0.59, 'r2': 0.06841355418412487, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 470.1896701388889, 'metric': 'mem'}\n",
      "[Server] training_time: 3.3326363563537598 s\n",
      "[Server] eval_time: 0.35414695739746094 s\n",
      "[Local] Memory usage: 303.453125 MB\n",
      "[Local] Total processing time: 10.7976 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 7.763513036803681, 'rmse': 2.7863081374470555, 'mape': 0.06262812112962074, 'mae': 2.17, 'smape': 6.34, 'r2': -0.010210006726382836, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 470.1896701388889, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 1.3784193056600513, 'rmse': 1.1740610314885898, 'mape': 0.01187805311317883, 'mae': 1.05, 'smape': 1.2, 'r2': -1.848363869280166, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 470.1896701388889, 'metric': 'mem'}\n",
      "[Server] training_time: 3.3523752689361572 s\n",
      "[Server] eval_time: 0.3469974994659424 s\n",
      "[Local] Memory usage: 303.8125 MB\n",
      "[Local] Total processing time: 10.8525 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 8.072527195420463, 'rmse': 2.841219314910495, 'mape': 0.0628061623120059, 'mae': 2.18, 'smape': 6.37, 'r2': -0.05041979239621286, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 471.17578125, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 1.3586611157509678, 'rmse': 1.1656161957312396, 'mape': 0.011177110253084387, 'mae': 0.99, 'smape': 1.13, 'r2': -1.8075355712228776, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 471.17578125, 'metric': 'mem'}\n",
      "[Server] training_time: 3.39976167678833 s\n",
      "[Server] eval_time: 0.3510322570800781 s\n",
      "[Local] Memory usage: 304.890625 MB\n",
      "[Local] Total processing time: 10.6978 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 7.923467800399218, 'rmse': 2.814865503074564, 'mape': 0.061916071601502094, 'mae': 2.11, 'smape': 6.1, 'r2': -0.031023767460955032, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 471.6892947635135, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 0.8000117739392658, 'rmse': 0.8944337728078395, 'mape': 0.008694470958662869, 'mae': 0.77, 'smape': 0.87, 'r2': -0.6531432943012776, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 471.6892947635135, 'metric': 'mem'}\n",
      "[Server] training_time: 3.317781686782837 s\n",
      "[Server] eval_time: 0.3455984592437744 s\n",
      "[Local] Memory usage: 305.265625 MB\n",
      "[Local] Total processing time: 7.6061 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 7.78961225730854, 'rmse': 2.7909876849080755, 'mape': 0.06315516100797956, 'mae': 2.17, 'smape': 6.34, 'r2': -0.013606110216745737, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 472.1892947635135, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 0.5184461195172788, 'rmse': 0.7200320267302551, 'mape': 0.006639726592118358, 'mae': 0.59, 'smape': 0.67, 'r2': -0.07131639040299143, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 472.1892947635135, 'metric': 'mem'}\n",
      "[Server] training_time: 3.3484764099121094 s\n",
      "[Server] eval_time: 0.3490126132965088 s\n",
      "[Local] Memory usage: 305.1875 MB\n",
      "[Local] Total processing time: 10.6999 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 7.641427825413405, 'rmse': 2.764313264703081, 'mape': 0.06206932219399456, 'mae': 2.14, 'smape': 6.24, 'r2': 0.005676062071994448, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 472.6892947635135, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 0.5877286086256492, 'rmse': 0.7666345991576752, 'mape': 0.0065585809595319, 'mae': 0.58, 'smape': 0.66, 'r2': -0.21448163623185956, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 472.6892947635135, 'metric': 'mem'}\n",
      "[Server] training_time: 3.3564603328704834 s\n",
      "[Server] eval_time: 0.3488953113555908 s\n",
      "[Local] Memory usage: 303.78125 MB\n",
      "[Local] Total processing time: 10.8009 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 8.25608466989336, 'rmse': 2.8733403331129015, 'mape': 0.06258155284922749, 'mae': 2.1, 'smape': 6.06, 'r2': -0.07430480381345239, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 473.1889391447368, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 0.5439365959336493, 'rmse': 0.7375205732273842, 'mape': 0.0065641490132276725, 'mae': 0.58, 'smape': 0.65, 'r2': -0.12398987788027283, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 473.1889391447368, 'metric': 'mem'}\n",
      "[Server] training_time: 3.348712205886841 s\n",
      "[Server] eval_time: 0.3487050533294678 s\n",
      "[Local] Memory usage: 304.328125 MB\n",
      "[Local] Total processing time: 8.2232 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 7.495172556881477, 'rmse': 2.7377312791582518, 'mape': 0.060934704427080766, 'mae': 2.11, 'smape': 6.16, 'r2': 0.024707206234049983, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 473.1896701388889, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 2.331544022585165, 'rmse': 1.5269394299005985, 'mape': 0.015502276361872274, 'mae': 1.37, 'smape': 1.57, 'r2': -3.81789955081024, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 473.1896701388889, 'metric': 'mem'}\n",
      "[Server] training_time: 3.311668634414673 s\n",
      "[Server] eval_time: 0.3433382511138916 s\n",
      "[Local] Memory usage: 304.40625 MB\n",
      "[Local] Total processing time: 7.6626 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 7.196064244973816, 'rmse': 2.682548088100904, 'mape': 0.060495027895707466, 'mae': 2.07, 'smape': 6.07, 'r2': 0.06362801545427355, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 473.6896701388889, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 0.6981465347983842, 'rmse': 0.8355516350282514, 'mape': 0.006841010200970008, 'mae': 0.6, 'smape': 0.69, 'r2': -0.44264909597348057, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 473.6896701388889, 'metric': 'mem'}\n",
      "[Server] training_time: 3.3609306812286377 s\n",
      "[Server] eval_time: 0.3459296226501465 s\n",
      "[Local] Memory usage: 302.328125 MB\n",
      "[Local] Total processing time: 10.7799 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 7.886406926613487, 'rmse': 2.808274724205858, 'mape': 0.06171578242924795, 'mae': 2.12, 'smape': 6.16, 'r2': -0.026201303020065625, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 474.17578125, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 0.43705050465770506, 'rmse': 0.6610979539052477, 'mape': 0.005815126392741784, 'mae': 0.51, 'smape': 0.58, 'r2': 0.09687940280148344, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 474.17578125, 'metric': 'mem'}\n",
      "[Server] training_time: 3.3224058151245117 s\n",
      "[Server] eval_time: 0.34162378311157227 s\n",
      "[Local] Memory usage: 304.5 MB\n",
      "[Local] Total processing time: 7.8536 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 7.646995200303949, 'rmse': 2.76532009002646, 'mape': 0.061197580530279724, 'mae': 2.09, 'smape': 6.07, 'r2': 0.004951619696621057, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 473.70280827702703, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 0.6245625230412565, 'rmse': 0.7902926818851712, 'mape': 0.007050290947557476, 'mae': 0.62, 'smape': 0.71, 'r2': -0.29059518931020567, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 473.70280827702703, 'metric': 'mem'}\n",
      "[Server] training_time: 3.324293613433838 s\n",
      "[Server] eval_time: 0.3436415195465088 s\n",
      "[Local] Memory usage: 302.953125 MB\n",
      "[Local] Total processing time: 7.5349 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[Server] metrics_cpu: {'mse': 8.622470932706863, 'rmse': 2.936404422539045, 'mape': 0.0632741679836032, 'mae': 2.15, 'smape': 6.18, 'r2': -0.12198000797253084, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 474.1896701388889, 'metric': 'cpu'}\n",
      "[Server] metrics_mem: {'mse': 0.5983041267921765, 'rmse': 0.7735012131808046, 'mape': 0.006951078298011301, 'mae': 0.61, 'smape': 0.7, 'r2': -0.23633487328444724, 'Model Size (MB)': 0.071935, 'Memory Usage (MB)': 474.1896701388889, 'metric': 'mem'}\n",
      "[Server] training_time: 3.3588786125183105 s\n",
      "[Server] eval_time: 0.3483307361602783 s\n",
      "[Local] Memory usage: 306.28125 MB\n",
      "[Local] Total processing time: 7.6342 s\n",
      "INFO:dataclay.client.api:Stopping client runtime\n",
      "INFO:dataclay.utils.backend_clients:Update loop has been cancelled.\n",
      "INFO:dataclay.client.api:Client runtime stopped\n"
     ]
    }
   ],
   "source": [
    "for _ in range(20):\n",
    "    !python train_dataclay.py --name_experiment \"Ryzen-Mac_server\" --client_experiment \"Ryzen-Mac_client\" --server_ip \"ceadaridg6.ucd.ie\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/config.py:181: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  settings = Settings()\n",
      "/Users/sebasmos/anaconda3/envs/api/lib/python3.10/site-packages/dataclay/client/api.py:156: UserWarning: directory \"/run/secrets\" does not exist\n",
      "  self.settings = ClientSettings(**settings_kwargs)\n",
      "INFO:dataclay.client.api:Starting client runtime\n",
      "INFO:dataclay.client.api:Creating event loop in new thread\n",
      "Starting event loop in new thread\n",
      "INFO:dataclay.client.api:Starting client runtime coroutine in event loop\n",
      "INFO:dataclay.client.api:Client runtime started\n",
      "INFO:dataclay.backend.client:SSL not configured\n",
      "[client ] model_memory_infer: 302.296875 MB\n",
      "[Server] prediction:  [[33.734493 87.43676 ]]\n",
      "[Server] inferencing_time:  0.0006086826324462891\n",
      "WARNING:dataclay.client.api:Client instance deleted without calling stop() for a clean shutdown\n"
     ]
    }
   ],
   "source": [
    "!python infer_offline.py"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "api",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
